#!/bin/bash

# Delay before starting. This must be 10 because send-notify is dumb on Ubuntu.
DELAY=10

DURATION=10

FOLDER="$HOME/Pictures"

TIME=$(date +"%Y-%m-%d_%H%M%S")

USERDUR=$(gdialog --title "Duration?" --inputbox "Please enter the screencast duration in seconds" 200 100 2>&1)
# Duration and output file
if [ $USERDUR -gt 0 ]; then
    D=$USERDUR
else
    D=$DURATION
fi

# xrectsel from https://github.com/lolilolicon/xrectsel
GEOMETRY=$(xrectsel "--x=%x --y=%y --width=%w --height=%h") || exit -1

notify-send -u normal -i info 'Byzanz' "Recording in ${DELAY}s"
sleep $DELAY
byzanz-record --delay=0 --duration=$D $GEOMETRY "$FOLDER/recording_$TIME.gif"
notify-send -t $((DELAY*1000)) -u normal -i info 'Byzanz' 'Done recording'
